spring.application.name=Daika
spring.data.mongodb.uri=mongodb+srv://Asifkhan:4554@cluster0.qckcacg.mongodb.net/daika?retryWrites=true&w=majority
logging.file.path=logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n
